"""bids table pickup otp agreed fare

Revision ID: 369a01122986
Revises: 151942cb0a07
Create Date: 2026-05-11 19:37:38.388161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369a01122986'
down_revision = '151942cb0a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('rider_id', sa.String(length=36), nullable=False),
    sa.Column('offered_fare', sa.Float(), nullable=False),
    sa.Column('counter_fare', sa.Float(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','accepted','rejected','countered','counter_accepted','counter_rejected','expired')", name='check_bid_status'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_otp', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('pickup_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agreed_fare', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('agreed_fare')
        batch_op.drop_column('pickup_verified')
        batch_op.drop_column('pickup_otp')

    op.drop_table('bids')
    # ### end Alembic commands ###
